{{- if .Values.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metricbeat.serviceAccount" . }}
  labels:
    app: "{{ template "metricbeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
